# Generated by Django 4.2.5 on 2023-09-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_description_alter_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='url_name',
            field=models.CharField(default='No url', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='This post has no description yet!', max_length=250),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(default='This tag has no description yet!', max_length=400),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
