# Generated by Django 4.2.5 on 2023-09-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tag_url_name_alter_post_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
