# Generated by Django 4.2.5 on 2023-10-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
